 --SAMPLE TABLE CREATION AND VALUES INSERTION
IF OBJECT_ID ('DBO.TABLE_CONFIG', 'U') IS NOT NULL  
	DROP TABLE TABLE_CONFIG;  
CREATE TABLE TABLE_CONFIG  
(  
	SCRAMBLE_ID INT IDENTITY(1,1),  
	TABLE_NAME VARCHAR (20),  
	COLUMN_NAME VARCHAR(30),
	SCRAMBLE_METHOD CHAR(30), 
	VALUE_TO_BE_CHANGED VARCHAR(30),
	LOG_TABLE_NAME VARCHAR(20) NULL,
	LOG_TABLE_DETAIL_NAME VARCHAR(20) NULL ,
	WHERE_CONDITION VARCHAR(1000) NULL
);
--	TRUNCATE TABLE TABLE_CONFIG
--	SELECT * FROM TABLE_CONFIG
CREATE TABLE PERSON1(
	PERSON_ID INT IDENTITY ,
	FIRST_NAME varchar(30) ,
	LAST_NAME varchar(30) ,
	COMPANY_NAME VARCHAR(100),
	EMAIL_ADDRESS VARCHAR(30),
	PHONE_NO BIGINT,
	PASS_WORD BIGINT,
	CITY VARCHAR(30),
	DATE1 DATE 
);
--DROP TABLE PERSON1
--SELECT * FROM PERSON1
CREATE TABLE PERSON_ADDRESS1(
	ADDRESS_ID INT IDENTITY,
	PERSON_ID INT,
	CITY VARCHAR(30),
	STATE_1 VARCHAR(30),
	PINCODE BIGINT,
	DATETIME1 DATETIME
);
--SET IDENTITY_INSERT PERSON_ADDRESS1 ON
--DROP TABLE PERSON_ADDRESS1
--SELECT * FROM PERSON_ADDRESS1
--INSERT INTO TABLE_CONFIG VALUES('PERSON1','DATE1',NULL,NULL,'LOG_1','LOG_2',null)
--								,('PERSON_ADDRESS1','DATETIME1',NULL,NULL,NULL,NULL,NULL)
--INSERT INTO PERSON1 VALUES('AAA','BBB','CCC','DDD',123,456,'XXXX','2023-02-01')
--						,('EEE','FFF','GGG','HHH',789,012,'AAAA','2023-02-01');
--INSERT INTO PERSON_ADDRESS1 VALUES(1,'XXXX','YYYY',123,'2023-02-01')
	--						,(1,'AAAA','NNNN',456,'2023-02-01');

			


	