--SCRAMBLE_LOG_CREATE_TABLE 'TABLE_A','TABLE_B'
--SELECT * FROM TABLE_A
--SELECT * FROM TABLE_B
--DROP TABLE TABLE_A
--DROP TABLE TABLE_B
IF EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE NAME = 'SCRAMBLE_LOG_CREATE_TABLE' AND TYPE ='P') DROP PROCEDURE SCRAMBLE_LOG_CREATE_TABLE
GO
CREATE PROCEDURE SCRAMBLE_LOG_CREATE_TABLE
		  @LOG_HEADER_TABLE				VARCHAR(40)
		, @LOG_DETAIL_TABLE				VARCHAR(40)
	AS 
	DECLARE @SQL_STMT VARCHAR(MAX)
	IF NOT EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE TYPE ='U' AND NAME = @LOG_HEADER_TABLE)
	BEGIN
		SET @SQL_STMT = 'CREATE TABLE '+@LOG_HEADER_TABLE+'
		(
			SCRAMBLE_ID					BIGINT IDENTITY(1,1)
			, TABLE_NAME				VARCHAR(30)
			, COLUMN_NAME				VARCHAR(30)
			, START_TIME				DATETIME
			, END_TIME					DATETIME
			, STATUS_VALUE				VARCHAR(20)
			, DESCRIPTION				VARCHAR(2000)
			CONSTRAINT PK_'+@LOG_HEADER_TABLE+' PRIMARY KEY (SCRAMBLE_ID)
		)'
--		PRINT(@SQL_STMT)
		EXEC(@SQL_STMT)	
	END;
	IF NOT EXISTS(SELECT 1 FROM SYS.OBJECTS WHERE TYPE ='U' AND NAME = @LOG_DETAIL_TABLE)
		BEGIN
				SET @SQL_STMT = 'CREATE TABLE '+@LOG_DETAIL_TABLE+'
				(
					SCRAMBLE_DETAIL_ID			NUMERIC(37,0) IDENTITY 	NOT NULL
					, SCRAMBLE_ID				BIGINT					NOT NULL
					, TABLE_NAME				VARCHAR(30)
					, COLUMN_NAME				VARCHAR(30)
					, SCRAMBLED_NO_OF_RECORDS	INT
					, START_TIME				DATETIME
					, END_TIME					DATETIME
					, STATUS_VALUE				VARCHAR(20)
					, SCRAMBLE_METHOD			VARCHAR(10)
					, REPLACE_VALUE				VARCHAR(100)
					CONSTRAINT PK_'+@LOG_DETAIL_TABLE+' PRIMARY KEY (SCRAMBLE_DETAIL_ID)
					CONSTRAINT FK_'+@LOG_DETAIL_TABLE+'_ARCHIVE_ID FOREIGN KEY (SCRAMBLE_ID) REFERENCES '+@LOG_HEADER_TABLE+'(SCRAMBLE_ID)
				)'
				EXEC(@SQL_STMT)	
--				PRINT(@SQL_STMT)
		END;